### ISSUE TITLE
Fix curl_multi_exec deprecated functionality error

### ISSUE THREAD

**Issue by edas11** [snowplow/snowplow-php-tracker#121]
**Describe the bug**
When calling `\Snowplow\Tracker\Tracker::flushEmitters` we get a PHP Fatal error `Deprecated Functionality: curl_multi_exec(): Passing null to parameter #2 ($still_running) of type int is deprecated in vendor/snowplow/snowplow-tracker/src/Emitters/CurlEmitter.php on line 173`. We call `flushEmitters` in `__destruct` method of a custom class which sends some order data.

**To Reproduce**
Call `\Snowplow\Tracker\Tracker::flushEmitters`.

**Expected behavior**
No PHP Fatal errors.

**Environment (please complete the following information):**
 - PHP 8.1
 - Magento 2.4.5
 - snowplow/snowplow-tracker 0.4.0. But it doesn't look like 0.5.0 has a fix for this.

**Comment by mscwilson** [comment]
Hi @edas11, really sorry that this issue got missed. We're looking into it now.

**Comment by mscwilson** [comment]
Hopefully this is fixed with version 0.6.1!
