### ISSUE TITLE
Add ability to validate requests being sent from the event log of Mountebank

### ISSUE THREAD

**Issue by jbeemster** [snowplow/snowplow-php-tracker#30]
Change the test suite around so that we:
- Validate event payloads based on the data we get back from Mountebank

Essentially we can ingest all of the events sent to our local Mountebank server back into the test suite.  If we could then test that the Payload we get back from Mountebank is what we assumed we sent out we can have end to end validation of the Request.

**Comment by mscwilson** [comment]
Closing because we'd do this with Micro these days
