### ISSUE TITLE
uniqid doesn't generate a valid UUID

### ISSUE THREAD

**Issue by adinardi** [snowplow/snowplow-php-tracker#39]
The tracker generates a UUID via [`uniqid`](https://github.com/snowplow/snowplow-php-tracker/blob/master/src/Tracker.php#L152), but that string won't validate in the Enrich process. EMR job fails [here](https://github.com/snowplow/snowplow/blob/f93812d9d78ae94ab0d1e26ffc050f4d9cf224af/3-enrich/scala-hadoop-shred/src/main/scala/com.snowplowanalytics.snowplow.enrich/hadoop/inputs/EnrichedEventLoader.scala#L109).

It would appear that the PHP tracker will need to include a UUID generator so that events can be accepted and processed.

**Comment by alexanderdean** [comment]
Ouch! Thanks for raising @adinardi. We will get this fixed. In the meantime, a quick workaround is to disable the line that adds the eid to the payload - then the Enrichment process will generate its own UUID...

**Comment by alexanderdean** [comment]
Let's fix this in a patch release, 0.2.1

/cc @yalisassoon

**Comment by alexanderdean** [comment]
What about https://github.com/ramsey/uuid ?

**Comment by jbeemster** [comment]
This has been done closing.
