### ISSUE TITLE
Add option to include page url with all events

### ISSUE THREAD

**Issue by adinardi** [snowplow/snowplow-php-tracker#46]
We'd like to be able to have the current page URL included with our PHP structured events and transactions, just like it is with the JS tracker.

It seems like a logical place to include it would be as part of Subject, like Useragent and the other per-request fields live already.

**Comment by alexanderdean** [comment]
Sounds like a good idea!

**Comment by smugkarl** [comment]
I needed this, so I built it myself. Would you like a PR?

**Comment by alexanderdean** [comment]
Yes please, sounds great!

**Comment by adatzer** [comment]
This is done (#78).
