### ISSUE TITLE
Current implementation relies on shell_exec()

### ISSUE THREAD

**Issue by smentek** [snowplow/snowplow-php-tracker#49]
It comes from "ramsey/uuid" on Uuid.php.

Is it how it is going to be? To use it on production application server one will have to enable 'shell_exec()'method? New version uses 'passthru()' instead but in my opinion it is still not a way to go.

function_exists from Tracker.php line 154 should check function from the namespace in with is used? Whatever it supposed to do it does not work and (constant?) UUID_TYPE_TIME just does not exist.

**Comment by alexanderdean** [comment]
Is there another way of generating a uuid in PHP?

**Comment by smentek** [comment]
What about: https://github.com/webpatser/laravel-uuid ? 
I have not check it but I would go with whatever that does not call to OS directly. If your library calls one of 'disabled functions' it is like red flag. I'm afraid to set it on prod current version...

**Comment by alexanderdean** [comment]
Looks promising!

**Comment by mscwilson** [comment]
Closing because this is very old.
