### ISSUE TITLE
UUID Library in composer is abandoned and has been replaced

### ISSUE THREAD

**Issue by iamthemouth** [snowplow/snowplow-php-tracker#57]
The referenced library in composer.json (rhumsaa/uuid 2.8.*) has been abandoned and replaced by ramsey/uuid. This causes dependency issues for us (and most likely many others).

https://github.com/ramsey/rhumsaa-uuid/
https://github.com/ramsey/uuid

**Comment by alexanderdean** [comment]
Thanks, scheduling

**Comment by dolfelt** [comment]
This is resolved in #60 if it can get merged.
