### ISSUE TITLE
Potential high load crash under Windows with FileEmitter

### ISSUE THREAD

**Issue by esquire900** [snowplow/snowplow-php-tracker#58]
Windows might crash under high load when using the FileEmitter. Using a simple implementation suggested by the documentation my windows machine slowly degrades when running a high load (in the range of dozens of logs a second) - up to the point where it completely hangs.

As I understood it from a senior dev, php in windows cannot spawn truly seperate processes, and slowly eats more and more resourceses when more processes are spawned.

Just a warning for those implementing this on windows - I managed to crash our servers with it

**Comment by alexanderdean** [comment]
Thanks for raising! @ihortom can you add a warning to the PHP Tracker documentation about this?

**Comment by ihortom** [comment]
@alexanderdean - done.

**Comment by alexanderdean** [comment]
Thanks, closing this ticket...
