### ISSUE TITLE
Lock Mountebank to v2.4.0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-php-tracker#67]
The latest versions of Mountebank are causing these strange errors:

```json
error creating imposter: [{"code":"bad data","message":"malformed stub request","data":"Object contains,exists has no method 'find'","source":{"responses":[{"is":{"statusCode":200,"body":"Successful Snowplow GET Request"}}],"predicates":[{"contains":{"path":"/i","method":"GET","body":""},"exists":{"query":{"e":true,"dtm":true,"p":true,"eid":true,"tv":true}}}]}},{"code":"bad data","message":"malformed stub request","data":"Object contains,exists has no method 'find'","source":{"responses":[{"is":{"statusCode":200,"body":"Successful Snowplow POST Request"}}],"predicates":[{"contains":{"path":"/com.snowplowanalytics.snowplow/tp2","method":"POST","query":{},"headers":{"Content-Type":"application/json; charset=utf-8"}},"exists":{"body":true}}]}}]
```

See https://travis-ci.org/snowplow/snowplow-php-tracker/jobs/247442944

**Comment by paulboocock** [comment]
We might not need to do this on Github Actions now, worth investigating the current state of Mountebank and whether we can close this for 0.4.0.

**Comment by adatzer** [comment]
Currently, latest release of Mountebank is 2.4.0
GitHub releases: https://github.com/bbyars/mountebank/releases
Docker hub: https://hub.docker.com/r/bbyars/mountebank/tags?page=1&ordering=last_updated
In Dockerfile we use v2.0.0, while Github Actions pull the latest. 
We could lock Mountebank version in both to 2.4.0 instead.
