### ISSUE TITLE
Add ability to write events to local socket

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow-php-tracker#7]
As opposed to using http or beanstalkd.

http://php.net/manual/de/function.socket-write.php

Idea is that a Go collector similar to https://github.com/LarsFronius/eventingestion_socket/blob/master/main.go could pick up those events and post on to Kinesis or Kafka.

/cc @jonalmeida @LarsFronius @ehartsuyker

**Comment by mscwilson** [comment]
Closing because this is very old.
