### ISSUE TITLE
Upgrade ramsey/uuid version constraint to allow v3 or v4

### ISSUE THREAD

**Issue by daviddeng2100** [snowplow/snowplow-php-tracker#87]
**Is your feature request related to a problem? Please describe.**
We are trying to upgrade our Laravel to 8, however we're stuck here:

snowplow/snowplow-tracker 0.3.0 requires ramsey/uuid 3.8.0 
Laravel/framework 8.x  requires ramsey/uuid ^4.0 

**Describe the solution you'd like**
It would be great if snowplow/snowplow-tracker supports ramsey/uuid ^4.0

Thank you!

**Comment by paulboocock** [comment]
Hey @daviddeng2100 

Thanks for raising this issue. I'll ensure this gets prioritised soon as it looks simple enough to bump.
